
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: healthcare
data:
  application.properties: |
    spring.datasource.url=jdbc:mysql://mysql:3306/healthcare_db
    spring.datasource.username=${MYSQL_USERNAME}
    spring.datasource.password=${MYSQL_PASSWORD}
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=false
    server.port=8080
    logging.level.root=INFO
